tryber/sd-06-project-frontend-online-store

- src/services/api.js
Requisito 01 - Criação da API Mercado Livre.
> [GRUPO 5] Implementacao Mercado Livre API

- package-lock.json
- package.json
- src/App.js
- src/components/SearchBar.js
**TASK:** _Req. 2 - Create empty product listing page_
**Status:** _Completed_
> [Group 12] Req.2 - Implemented search bar and default message

- src/App.css
- src/App.js
- src/__tests__/requirement1.test.js
- src/services/api.js
fetch api for categories 
fetch api for products using categoryId and query
req 1
> Main group 21 fetch api

- src/App.js
- src/services/api.js
Grupo 10:
Daniele Perse
Isabela Rosa
Lucas Gomide
William Gomes
> primeiro commit grupo 10

- src/App.js
- src/services/api.js
Fizemos as duas requisições API's
> Requisito 2

- src/App.js
- src/services/api.js
> Group 20 - FrontEnd Online Store - first requirement

- package-lock.json
- package.json
- src/App.js
- src/components/ProductListing.jsx
> [Group 01 - CLT] - Search Field

- src/App.js
- src/services/api.js
Fetch request implemented on services/api to return categories from Mercado Livre.
> Task 0 - implementing api request

- src/App.js
> Main group 21 search field

- package-lock.json
- package.json
- src/App.js
- src/pages/ProductList.jsx
> Feature Requiriment 02

- src/App.js
- src/components/Home.js
Tiago Berwanger
Patty Garcia
Lais Gurgel
Elisa Camillo
> Group 20 - FrontEnd Online Store

- package-lock.json
- package.json
- src/App.js
- src/PagInicial.js
Apenas retirando o conteúdo padrão do componente App.
> Req 2: Primeiro commit retirando conteudo do componente App

- src/services/api.js
Implementing mercado livre api function
> Requirement 1

- src/App.js
- src/pages/SearchEngine.js
> [GRUPO 18] Cria tela de busca

- package-lock.json
- package.json
- src/App.js
- src/Home.js
**PRIORIDADE 0** - Criar o campo de busca da tela principal, a listagem de produtos, inicialmente vazia. A listagem vazia deve conter a mensagem "Digite algum termo de pesquisa ou escolha uma categoria" (veja os detalhes do card).
- [Tela principal - Antes da busca](https://github.com/my-org/my-repo/tree/master/wireframes/card_02.png)
**Observações técnicas**
A tela básica da plataforma é a tela de **listagem de produtos**, onde quem usa buscará o que quer para adicionar ao carrinho e filtrará suas buscas.
**O que será avaliado:**
> Main group 27 02requisito pagina listagem vazia

- src/services/api.js
> Fetch API MercadoLivre

- package-lock.json
- package.json
- src/App.js
- src/Pages/Home.js
- src/services/Routes.jsx
Requisito 2º Criaçao da pagina Home, Serviço Routes.jsx e emplementaçao App.jS
> Grupo 16 - REQUISITO 2

- package-lock.json
- package.json
- src/App.js
- src/Home.js
- src/services/api.js
Criado o campo de busca da página principal. Detalhe foi feita a renderização do componente Home - usando a sintaxe de função ao invés de classe, devido ao ESLINT.
> Requisito 2 - Criado campo de busca da página principal

- .eslintrc.json
- README.md
- package-lock.json
- package.json
- src/App.js
- src/services/ShopCart.js
- src/services/ShopList.js
Analise do teste do requisito 3
> Main group 21 shop cart button

- src/Home.js
- src/ListCards.js
- src/StoreProductCard.js
- src/services/api.js
**PRIORIDADE 1** - Criar a listagem de produtos. Fazer a exibição resumida do produto (o "card" que aparece na listagem). A exibição deve ter título, foto e preço. Fazer requisição à API do Mercado Livre enviando os termos buscados por quem usa e usar o retorno para fazer a listagem dos produtos. Se a busca não retornar resultados, gerar a tela correspondente com o texto "Nenhum produto foi encontrado" (veja os detalhes no card).
- [Tela principal - Após a busca](https://github.com/my-org/my-repo/tree/master/wireframes/card_05.1.png)
- [Tela principal - Nenhum produto encontrado](https://github.com/my-org/my-repo/tree/master/wireframes/card_05.2.png)
**Observações técnicas**
A alma do site é a sua lógica de busca e listagem de produtos. Após digitar seus termos na caixa de busca uma …
> Group 27 - PR for Task 5 - Search By Terms and Receive a Products List

- src/App.js
- src/HomePage.js
- src/ShoppingCart.js
the shopping cart button and the respective component were created
> [Group 30] Add shopping cart - req 3

- src/App.css
- src/App.js
- src/components/CategoriesSideBar.js
- src/components/index.js
- src/components/style_sheets/CategoriesSideBar.css
Creating category sidebar:
1) New component created
2) Started CSS styling
> Main Group 29 - :sparkle: - Task 4 - Implementing Category sidebar

- src/App.js
- src/components/CategoriesListing.jsx
- src/components/ProductListing.jsx
> :sparkles: Priority 1 - Menu Categories

- src/App.js
- src/ButtonShoppingCart.js
**PRIORIDADE 1** - Criar o botão de carrinho de compras na tela principal, de listagem de produtos, e criar uma tela para o carrinho de compras, inicialmente vazio (veja os detalhes do card).
- [Tela do carrinho de compras](https://github.com/my-org/my-repo/tree/master/wireframes/card_03.png)
- [Tela principal - Com botão do carrinho de compras](https://github.com/my-org/my-repo/tree/master/wireframes/bonus_shopping_cart_button.png)
**Observações técnicas**
Quem usa o site irá adicionar produtos em seu carrinho de compras e finalizar a compra. A listagem de produtos deve ter um ícone de carrinho que, ao ser clicado, leva à página do carrinho. Inicialmente, o carrinho deverá estar vazio.
**O que será avaliado:**
> Criando componente ButtonShoppingCart.js e exportanto para App.js

- src/App.js
- src/components/CategoryList.js
- src/components/Home.js
- src/services/api.js
- src/styles/CategoryList.css
Lista de Categorias (Requisito 4)
By: Tio RamireZ xD
> Implementation of Category List

- src/App.css
- src/App.js
- src/MainPage.js
Sidebar with list of categories.
> Group-24: Requirement-4 complete

- .eslintrc.json
- README.md
- src/App.js
- src/Home.js
- src/components/ShoppingCartButton.js
- src/pages/ShoppingCart.js
Main group 26 - Requirement 3 - Shopping Cart
> Main group 26 - Requirement 3

- src/App.js
- src/services/api.js
This branch contains the first requirement of the project. More especifically, it contains the code to handle the requests to Mercado Livre's API.
> Group 2 - Implement requirement 1

- src/functions/list_categories.js
- src/pages/PaginaInicial.jsx
Adicionado a listagem de categorias.
> [GRUPO 5] Requisito 4

- src/App.js
- src/components/ListCategory.js
- src/pages/Home.js
Requisite 4 - fetch list categories from API. It's all good with the local tests. A change has been made:
- Create a new component with the name ListCategory.js;
- Added ListCategory components to App.js
- I made a list use ```<li>``` element, but feel free to change for another element.
For more information or help, just hit me on Slack.
> [Group 18] List Category - Req. 4

- src/App.js
- src/HomePage.js
- src/Product.js
- src/ProductList.js
Created Components ProductList and Product
> :sparkles: [GROUP-30] - Product List

- src/App.js
- src/components/SearchBar.js
- src/components/productList.js
- src/services/api.js
> filter category

- src/pages/ProductList.jsx
- src/services/api.js
> Requirement 03 changes ProductList

- src/App.css
- src/App.js
- src/components/CategoriesSideBar.js
- src/components/SearchedItems.js
- src/pages/Home.js
- src/pages/style/home.css
Implementando filtro por categoria
> Main group 28 task6

- src/Home.js
- src/ListCategories.js
> Main group 26 - Requirement 4

- src/components/ProductCard.js
- src/components/index.js
- src/pages/ShopList.js
- src/services/api.js
Criaçao do componente ProductCard.js, criaçao do codigo para renderizaçao desses componentes a partir do resultado da busca
> Requisito 5: fetch products

- src/pages/ShopList.js
- src/services/api.js
Requisito 4
Adicionando lista de categorias ao componente ShopList na path raiz `/`.
> Main group 21 categories list

- src/components/CategoryList.js
- src/pages/Home.js
Implementação do filtro por categoria
By: - Tio RamireZ xD
- Ana Higo
> Implementation of Filter By Category

- .eslintrc.json
- src/App.css
- src/pages/Home.css
- src/pages/Home.jsx
This branch contains the fourth requirement of the project. More especifically, it contains the code to obtain and render Mercado Livre's product categories to the Home screen.
> Group 2 - Implement requirement 4

- src/components/ListCategories.js
- src/pages/Home.js
Implementing filter by categories
> main group 26 requirement 6

- package-lock.json
- package.json
- src/CategoryListener.js
- src/Home.js
**PRIORIDADE 2** - Como pessoa usuária, eu quero clicar em uma categoria e ver a listagem de produtos ser filtrada de  acordo com os produtos daquela categoria (veja os detalhes no card).
**Observações técnicas**
_**### A página, agora, deve poder usar as categorias recuperadas da API para filtrar os produtos buscados. Os termos e as categorias inseridas por quem usa devem ser usados em conjunto para filtragens mais específicas.**_
**O que será avaliado:**
> Main group 27 06requisito filtrar categoria

- package.json
- src/App.css
- src/App.js
- src/components/ProductCard.js
- src/components/ProductsList.js
- src/components/SearchBar.js
- src/services/api.js
**Task:** _Req. 5_
**Status:** _Incomplete_
> [Group 12] Req. 5 - Render product list using search mechanism.

- src/App.css
- src/App.js
- src/components/Loading.js
- src/components/ProductCard.js
- src/components/index.js
- src/pages/ProductDetails.js
- src/pages/ShopList.js
- src/pages/index.js
- src/services/api.js
Adding product details page, adding function at api.js to fetchProduct . requirement 7.
> Main group 21 product details

- src/App.js
- src/components/Home.jsx
- src/components/Product.jsx
- src/components/ProductList.jsx
- src/css/Product.css
- src/services/api.js
Requirement 5  incomplete, open to be solved group-23
> requirement 5 inclomplete

- src/components/CategoriesList.js
- src/pages/Main.js
Is rendering the products as expected. However, is not being accepted by the evaluator.
**Error:**
**Edit:**
The error was giving to the use of `<select>` instead of `<input type="radio>` (Req. 4)
> Req.6 - Is working, but test isn't accepeting

- src/App.js
- src/Home.js
- src/Loading.js
- src/ProductDetails.js
- src/StoreProductCard.js
- src/services/api.js
add funcionalidade exibição detalhada
> add funcionalidades requisito 7

- src/ButtonShoppingCart.js
- src/CategoryListener.js
- src/Home.js
- src/IconCart.js
- src/ListCards.js
- src/ProductDetails.js
- src/ShoppingCart.js
- src/StoreProductCard.js
13. VER JUNTO AO ÍCONE DO CARRINHO A QUANTIDADE DE PRODUTOS DENTRO DELE, EM TODAS AS TELAS EM QUE ELE APARECE
PRIORIDADE 4 - Adicionar ao ícone do carrinho, em todas as telas em que ele aparece, um número com a quantidade de produtos adicionados (veja os detalhes no card).
Tela - Listagem de produtos com carrinho e quantidade
Observações técnicas
A partir de uma pesquisa com usuários e concorrentes, identificamos que existe a necessidade de uma visualização da quantidade de produtos do carrinho de uma forma dinâmica e acessível.
Adicione o atributo data-testid com o valor shopping-cart-size no elemento que contém a quantidade de produtos presente na lista.
A quantidade a ser exibida é o número total de itens, ou seja, se a pessoa adiciona o produto1 5 vezes e o produto2 2 vezes, o valor a …
> Group 27 - PR Task 13 - Implementation of quantity of products on cart with the cart icon

- src/App.js
- src/CartProductCard.js
- src/Header.js
- src/Home.js
- src/ListCards.js
- src/ProductDetails.js
- src/ShoppingCart.js
- src/StoreProductCard.js
9. ADICIONAR UM PRODUTO AO CARRINHO A PARTIR DE SUA TELA DE EXIBIÇÃO DETALHADA
PRIORIDADE 3 - Na tela de listagem de produtos, permitir adicionar o produto ao carrinho (veja os detalhes no card).
Tela principal - Adicionar ao carrinho na exibição detalhada
Observações técnicas
Poder adicionar produtos ao carrinho a partir de sua tela de exibição detalhada será um canal importante de conversões de venda.
Adicione o atributo data-testid com o valor product-detail-add-to-cart no elemento que possui a ação de adicionar o produto ao carrinho de compras.
Adicione o atributo data-testid com o valor shopping-cart-product-name no elemento que possui o nome do produto na tela do carrinho de compras. Você deve adicionar esse atributo para todos os produtos.
Adicione o atributo data-testid com o …
> Group 27 - PR Task 9 - feat: Implementation of Task 9 - add product on cart from the product page

- src/components/PreviousReview.js
- src/components/PreviousReviewStar.js
- src/components/ProductReviewForm.js
- src/components/StarRating.js
- src/components/style_sheets/CategoriesSideBar.css
- src/components/style_sheets/PreviousReview.css
- src/components/style_sheets/ProductReviewForm.css
- src/pages/CardDetails.js
Task 11:
Criando formulário de feedback no cliente na página do produto
> Main group 28 leandro parisi task11

- src/App.js
- src/components/Home.js
- src/components/ProductItem.js
- src/components/ProductList.js
- src/components/ShoppingCart.js
Forgot the small commits "rule". I've made changes to many files, trying to implement the add-to-cart button on the home product list, not working properly yet (still waiting for items 6 and 7 to be done to adapt my code before facing merge-conflicts)
> [Group 22] FEAT: add to cart button on home list

- src/App.js
- src/Checkout.js
- src/PaymentMethod.js
- src/ShoppingCart.js
requisito 12 add funcionalidades
> requisito 12 add funcionalidades

- package.json
- src/App.css
- src/components/Loading.js
- src/components/Product.js
- src/components/index.js
- src/pages/ProductList.js
O códgio foi refatorado para melhorar a funcionalidade de busca de produtos, utilizando os dois tipos de filtros possíveis ao mesmo tempo.
> [GROUP 19] Melhoria na funcionalidade de busca de produtos *

- src/App.js
- src/components/Categories.jsx
- src/components/Home.jsx
- src/components/Product.jsx
- src/components/ProductDetails.jsx
- src/services/api.js
> requirement 6 and 7 solved

- src/components/ListCategory.js
- src/components/ProductList.js
- src/components/ProductsCard.js
- src/components/SearchEngine.js
- src/pages/Home.js
- src/styles/Home.css
- src/styles/ListCategories.css
- src/styles/ProductList.css
- src/styles/ProductsCard.css
- src/styles/SearchEngine.css
Modified files:
- ListCategory.js;
- ProductList.js;
- ProductsCard.js;
- SearchEngine.js;
- Home.js;
- Home.css
- ProductsCard.css;
New files:
- ListCategories.css;
- ProductList.css;
- SearchEngine.css;
ps: All modifications made were only on the Layout. No changes were made to the operating logic.
> [GRUPO 18] Layout do Projeto(Req 1 ao 7) - Parte 1 - Ajuste padrão baseado no protótipo

- src/App.css
- src/App.js
- src/components/Cart.js
- src/components/PaymentForm.js
- src/components/ProductCard.js
- src/components/index.js
- src/pages/Checkout.js
- src/pages/ShopCart.js
- src/pages/ShopList.js
- src/pages/index.js
- criar a tela de checkout
- resumo da compra
- formulario do comprador
- botao para finalizar compra
> Main group 21 checkout

- src/App.css
- src/App.js
- src/components/Cart.js
- src/components/CategoryList.js
- src/components/ProductCard.js
- src/components/RenderProduct.js
- src/components/index.js
- src/pages/ProductDetails.js
- src/pages/ShopCart.js
- src/pages/ShopList.js
Add product to shopping cart from shop list. Requirement 8.
> Main group 21 shoplist add product

- src/components/Cart.js
- src/components/ProductCard.js
- src/components/Shipping.js
- src/pages/ShopCart.js
- src/pages/ShopList.js
> Main group 21 quantity limit

- src/App.js
- src/components/ProductCard.js
- src/components/ProductSpecs.js
- src/pages/ProductsDetails.js
> Main group 26 - requirement 7

- src/components/ShoppingCart.js
[Group 22] FEAT: requirement 10
> [Group 22] FEAT: requirement 10

- src/App.js
- src/CartProductCard.js
- src/Home.js
- src/ListCards.js
- src/ProductDetails.js
- src/ShoppingCart.js
- src/StoreProductCard.js
10. VISUALIZAR A LISTA DE PRODUTOS ADICIONADOS AO CARRINHO EM SUA PÁGINA E MANIPULAR SUA QUANTIDADE
PRIORIDADE 3 - Adicionar lista de produtos ao carrinho, com valor total ao final. Criar botões (-) e (+) para cada produto do carrinho, permitindo alterar a quantidade desejada de cada produto. A quantidade não pode ser negativa. Criar também botão (X) para remover produtos do carrinho e botão para finalizar a compra (veja os detalhes no card).
Tela - Carrinho de compras com quantidades
Observações técnicas
São operações básicas de carrinho a alteração da quantidade de um determinado produto nele e a visualização de tudo o que foi adicionado, com a soma dos valores.
Adicione elementos na página do carrinho de compras para aumentar ou diminuir a quantidade de cada produto presente no …
> Group 27 - PR for Task 14 - Limit quantity according to available quantity

- src/App.js
- src/components/ProductDetails.jsx
- src/components/ShoppingCart.jsx
Implementation of handle possibility to add item in cart from details page.
> [Group-01 CLT ] :sparkles: Handle quantity of items added to cart

- src/App.js
- src/components/ProductCard.js
- src/pages/Cart.js
- src/pages/ProductDetails.js
- src/pages/ProductList.js
Ainda restam resolver avisos sobre as props.
E também que quando adiciona item ao carrinho, a tela reinicia.
> [GRUPO 19] Desenvolvendo o requisito 9

- src/App.js
- src/components/Checkout.js
- src/components/ShoppingCart.js
Checkout button implemented, checkout page implemented
> [Group 22] FEAT: Checkout page

- src/ProductDetails.js
- src/ProductEvaluator.js
- src/StarsRating.js
> requisito11 add funcionalidade

- src/components/AddCartButton.js
- src/components/ProductCard.js
- src/components/ShoppingCartButton.js
- src/pages/Home.js
- src/pages/ShoppingCart.js
> Main group 26 requirement 8

- src/App.css
- src/App.js
- src/components/Cards.js
- src/components/CategoryDisplay.jsx
- src/components/ProductList.jsx
- src/pages/CardDetail.jsx
> [Group 17][Requisito 7]

- src/components/AddToCartButton.js
- src/components/ProductList.js
- src/components/ProductsCard.js
- src/pages/Home.js
- src/pages/ShoppingCartPage.js
> [GRUPO 18] Requisito 8

- src/pages/CardDetail.jsx
> [Group 17][Requisito 9]

- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/pages/Home.jsx
- src/pages/ShoppingCart.jsx
This branch contains the eighth requirement of the project. More especifically, it contains the code to add products listed on the home page to the shopping cart.
> Group 2 - add products from home to shopping cart

- src/App.css
- src/App.js
- src/components/CategoryList.js
- src/components/Home.js
- src/components/ProductDetails.js
- src/components/ProductItem.js
- src/components/ShoppingCart.js
- src/index.css
> Main group 22 CSS

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/App.scss
- src/components/ProductCard.js
- src/components/Shipping.js
new shoplist design
changin some JSX logic (implementing button at productCard)
> Shoplist css

- src/App.js
- src/components/Product.js
- src/components/ProductCard.js
- src/pages/Cart.js
- src/pages/ProductDetails.js
- src/pages/ProductList.js
Removendo erros de props de console
Refatoração de items passados para o carrinho atraves de localStorage ao inves de props, estava causando muitos comportamentos indesejados.
> [GRUPO 19] Refatorando até o requisito 09

- src/pages/ProductList.js
Removido o uso desenecessário do await na função handleQuery
> [GROUP 19] minor fix

- src/Components/ShoppingCart.js
- src/Pages/HomePage.js
- src/Pages/ProductDetail.js
- src/Pages/ProductList.js
> [GROUP-30] :bug: Fixed bug LocalStorage

- src/components/Cart.jsx
- src/components/Home.jsx
- src/components/Product.jsx
- src/components/ProductDetails.jsx
Requirement 08 and 09 solved, waiting for aprovement
> Main group 23 requirement 08

- src/App.js
- src/components/ProductCard.js
- src/components/ShoppingCartButton.js
- src/pages/Home.js
- src/pages/ProductsDetails.js
- src/pages/ShoppingCart.js
> Main group 26 - Requirement 9

- src/Components/Product.js
free shipping notice was added
> [GROUP-30] add free shipping warning

- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
> feat: review product spot add

- src/App.css
- src/App.js
- src/components/ProductCard.js
- src/components/ProductCardList.js
- src/pages/Home.js
- src/pages/ProductsDetails.js
- src/pages/ShoppingCart.js
Handle products quantity price.
> Main group 26 requirement 10

- src/App.css
- src/App.js
- src/components/CartItem.js
- src/components/Product.js
- src/components/ProductCard.js
- src/components/ShoppingCart.js
- src/components/index.js
- src/pages/Cart.js
- src/pages/Checkout.js
- src/pages/ProductDetails.js
- src/pages/ProductList.js
- src/services/CartSize.js
Dentro da pagina de carrinho, alterar quantidades sem exceder quantidade disponível de items
> [GRUPO 19] Requisito 14

- src/App.css
- src/App.js
- src/components/CartItem.js
- src/components/Product.js
- src/components/ProductCard.js
- src/components/ShoppingCart.js
- src/components/index.js
- src/pages/Cart.js
- src/pages/Checkout.js
- src/pages/ProductDetails.js
- src/pages/ProductList.js
- src/services/CartSize.js
Adicionar items atualiza o display do carrinho com a quantidade de itens.
Tem algo que não passa no evaluator a partir da tela de detalhes.
Mas na prática tudo funciona.
> [GRUPO 19]Requisito 13

- src/App.css
- src/pages/ProductDetails.js
Ainda de forma bem simples. Uma textarea para avaliação, na pagina de detalhes do produto.
> [GOUPO19] Requisito 11

- src/App.css
- src/App.js
- src/components/CartItem.js
- src/pages/Cart.js
- src/pages/Checkout.js
- src/pages/ProductDetails.js
Form de finalizar compra na pagina nova, ainda bem simples.
> [Group19] Requisito 12

- src/components/ProductCard.jsx
- src/pages/ShoppingCart.jsx
This branch contains the fourteenth requirement of the project. More especifically, it contains the code to limit the quantity of a product the user can order so that it never is greater than what is available in that seller's own stock.
> Group 2 - limit product quantity in shopping cart
